/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.orioncraftmc.orion.api

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
